title:  OpMAP
tagline:  analysis and visualization of large opinion spaces
author:
  name: 'OpMAP team'
  mail:  opinionspacemap@gmail.com

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-opmap'

#google-ID: 'UA-80213386-1'

menu:
- {name: 'Methodology', url: 'methodology.html'}
- {name: 'Veggie-debate', url: 'veggie-debate.html'}
- {name: 'Team', url: 'team.html'}


social:
- {icon: 'github', link: 'https://github.com/opmap/'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
#- {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'envelope', link: 'mailto:opinionspacemap@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
